// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icqjadkcarpgayjtercn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljcWphZGtjYXJwZ2F5anRlcmNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxMjA3NTEsImV4cCI6MjA4NTY5Njc1MX0.OAD__iDe_ZC9KP_AaVb7l8clE7SJ3JaNn4egRUXnpv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});